---
title: "03_construct_figuretable_merger"
author: "Suguru Otani"
date: "2022/7/2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
library(modelsummary)
options(modelsummary_format_numeric_latex = "plain") # for modelsummary output
```


```{r cars, warning=FALSE}
operator_level_entry_exit_merger_CIY <-
  readRDS(file = "../output/operator_level_entry_exit_merger_CIY.rds")
operator_level_entry_exit_merger_HBdata <-
  readRDS(file = "../output/operator_level_entry_exit_merger_HBdata.rds")
operator_level_entry_exit_merger_IHS <-
  readRDS(file = "../output/operator_level_entry_exit_merger_IHS.rds")
matching_pair_year_CIY <-
  readRDS(file = "../output/matching_pair_year_CIY.rds")
matching_pair_year_IHS <-
  readRDS(file = "../output/matching_pair_year_IHS.rds")
matching_pair_year_HBdata <-
  readRDS(file = "../output/matching_pair_year_HBdata.rds")
HB_data <-
  readRDS(file = "../output/HB_data.rds")
IHS_data <-
  readRDS(file = "../output/IHS_data.rds")
```


# Entry, exit, and mergers {.tabset}

## Operator {.tabset}

### CIY {.tabset}

#### Merger list {.tabset}

<!-- ##### Market-level -->

<!-- ```{r, echo=FALSE} -->
<!-- operator_level_entry_exit_merger_CIY_for_output <- -->
<!--   operator_level_entry_exit_merger_CIY %>%  -->
<!--   dplyr::filter( -->
<!--     dummy_merged_until_data_period == 1 -->
<!--   ) %>%  -->
<!--   dplyr::arrange(start) %>%  -->
<!--   dplyr::mutate( -->
<!--     merging_firm_color = -->
<!--       ifelse( -->
<!--         is.na(merging_firm) == 1 & -->
<!--           dummy_merged_until_data_period == 0, -->
<!--              operator, -->
<!--              merging_firm) -->
<!--   ) -->
<!-- operator_level_entry_exit_merger_CIY_for_output %>%  -->
<!--   kableExtra::kable() %>%  -->
<!--   kableExtra::kable_styling() -->

<!-- ``` -->

<!-- ##### Industry-level -->

```{r, echo=FALSE}
merger_list <-
  matching_pair_year_CIY %>% 
  dplyr::select(
    seller_name,
    buyer_name,
    end
  ) %>% 
  dplyr::rename(
    `Seller` = seller_name,
    `Buyer` = buyer_name,
    `Year` = end
  ) %>% 
  dplyr::mutate(
    `Buyer` =
      ifelse(
        `Buyer` == "P&O Containers",
        "P\\&O Containers",
        `Buyer`
      )
  )
merger_list %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()

merger_list %>% 
  kableExtra::kbl(
    format = "latex",
    booktabs = TRUE,
    escape = FALSE,
    linesep = ""
  ) %>% 
  kableExtra::save_kable(
    file = here::here("figuretable/merger_list_CIY.tex")
  )
```

#### Summary statistics

```{r, echo=FALSE}
seller_data <-
  matching_pair_year_CIY %>% 
  dplyr::select(
    #seller_name,
    seller_operator_age_normalized,
    seller_cumsum_TEU_normalized
  ) %>% 
  dplyr::rename(
    `Age (Normalized)` = seller_operator_age_normalized,
    `Size TEU (Normalized)` = seller_cumsum_TEU_normalized
  )
buyer_data <-
  matching_pair_year_CIY %>% 
  dplyr::select(
    #buyer_name,
    buyer_operator_age_normalized,
    buyer_cumsum_TEU_normalized
  ) %>% 
  dplyr::rename(
    `Age (Normalized)` = buyer_operator_age_normalized,
    `Size TEU (Normalized)` = buyer_cumsum_TEU_normalized
  ) 
target_date_CIY <-
  rbind(
    seller_data,
    buyer_data
    ) %>% 
  dplyr::mutate(
    data = "CIY (1966-1990)"
  )
f <- 
  (`Age (Normalized)` +
     `Size TEU (Normalized)`) ~ 
  N + (mean + sd + min + max)*Arguments(na.rm = TRUE)
modelsummary::datasummary(
  f,
  data = target_date_CIY
  )
target_date_CIY %>% 
  modelsummary::datasummary(
    f,
    escape = FALSE,
    data = .,
    output = "latex_tabular"
  ) %>% 
  gsub("\\multicolumn.*\\\\", "", .) %>% 
  kableExtra::save_kable(
    file = here::here("figuretable/summary_statistics_of_firms_CIY.tex")
  )
```



#### Overall Transition

```{r, echo=FALSE}
operator_level_entry_exit_merger_CIY_for_output <-
  operator_level_entry_exit_merger_CIY %>% 
  dplyr::distinct(
    operator,
    .keep_all = TRUE
  ) %>% 
  dplyr::arrange(start) %>% 
  dplyr::mutate(
    merging_firm_color =
      ifelse(
        is.na(merging_firm) == 1 &
          dummy_merged_until_data_period == 0,
        operator,
        merging_firm
        )
  )
ggplot(operator_level_entry_exit_merger_CIY_for_output, 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator, -start), 
           yend = reorder(operator, -start)
           )) +
  theme_classic() +
  geom_segment(aes(colour=merging_firm)) +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("operator")

operator_level_entry_exit_merger_CIY_for_output %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()

```



### IHS Shipdetails {.tabset}

#### Merger list

```{r, echo=FALSE}
merger_list <-
  matching_pair_year_IHS %>% 
  dplyr::select(
    seller_name,
    buyer_name,
    end
  ) %>% 
  dplyr::rename(
    `Seller` = seller_name,
    `Buyer` = buyer_name,
    `Year` = end
  ) %>% 
  dplyr::mutate(
    `Seller` =
      ifelse(
        `Seller` == "ROYAL P&O NEDLLOYD NV (KONINKL",
        "ROYAL P\\&O NEDLLOYD NV",
        `Seller`
      )
  ) %>% 
  dplyr::mutate(
    `Seller` =
      ifelse(
        `Seller` == "IMC SHIPPING CO PTE LTD (IMCSC",
        "IMC SHIPPING CO PTE LTD",
        `Seller`
      )
  ) %>% 
  dplyr::mutate(
    `Buyer` =
      ifelse(
        `Buyer` == "IMC SHIPPING CO PTE LTD (IMCSC",
        "IMC SHIPPING CO PTE LTD",
        `Buyer`
      )
  )
merger_list %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()

merger_list %>% 
  kableExtra::kbl(
    format = "latex",
    booktabs = TRUE,
    escape = FALSE,
    linesep = ""
  ) %>% 
  kableExtra::save_kable(
    file = here::here("figuretable/merger_list_IHS.tex")
  )
```


#### Summary statistics

```{r, echo=FALSE}
seller_data <-
  matching_pair_year_IHS %>% 
  dplyr::select(
    #seller_name,
    seller_operator_age_normalized,
    seller_cumsum_TEU_normalized
  ) %>% 
  dplyr::rename(
    `Age (Normalized)` = seller_operator_age_normalized,
    `Size TEU (Normalized)` = seller_cumsum_TEU_normalized
  )
buyer_data <-
  matching_pair_year_IHS %>% 
  dplyr::select(
    #buyer_name,
    buyer_operator_age_normalized,
    buyer_cumsum_TEU_normalized
  ) %>% 
  dplyr::rename(
    `Age (Normalized)` = buyer_operator_age_normalized,
    `Size TEU (Normalized)` = buyer_cumsum_TEU_normalized
  )
target_date_IHS <-
  rbind(
    seller_data,
    buyer_data
    ) %>% 
  dplyr::mutate(
    data = "IHS (1991-2005)"
  )
f <- 
  (`Age (Normalized)` +
     `Size TEU (Normalized)`) ~ 
  N + (mean + sd + min + max)*Arguments(na.rm = TRUE)
modelsummary::datasummary(
  f,
  data = target_date_IHS
  )
target_date_IHS %>% 
  modelsummary::datasummary(
    f,
    escape = FALSE,
    data = .,
    output = "latex_tabular"
  ) %>% 
  gsub("\\multicolumn.*\\\\", "", .) %>% 
  kableExtra::save_kable(
    file = here::here("figuretable/summary_statistics_of_firms_IHS.tex")
  )
```



#### Overall Transition

```{r, echo=FALSE}
IHS_data_for_output <-
  IHS_data %>% 
  dplyr::group_by(operator) %>% 
  dplyr::summarise(
    start = min(year),
    end = max(year)
  ) %>% 
  dplyr::ungroup() %>%
  dplyr::arrange(start) 

ggplot(IHS_data_for_output, 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator, -start), 
           yend = reorder(operator, -start)
           )) +
  theme_classic() +
  geom_segment() +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("operator")

ggplot(IHS_data_for_output %>% 
         dplyr::filter(start <= 1992), 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator, -start), 
           yend = reorder(operator, -start)
           )) +
  theme_classic() +
  geom_segment() +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("operator")

ggplot(IHS_data_for_output %>% 
         dplyr::filter(start <= 1995&
                         start >= 1993), 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator, -start), 
           yend = reorder(operator, -start)
           )) +
  theme_classic() +
  geom_segment() +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("operator")

ggplot(IHS_data_for_output %>% 
         dplyr::filter(start <= 1998&
                         start >= 1996), 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator, -start), 
           yend = reorder(operator, -start)
           )) +
  theme_classic() +
  geom_segment() +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("operator")

ggplot(IHS_data_for_output %>% 
         dplyr::filter(start <= 2001&
                         start >= 1999), 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator, -start), 
           yend = reorder(operator, -start)
           )) +
  theme_classic() +
  geom_segment() +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("operator")

ggplot(IHS_data_for_output %>% 
         dplyr::filter(start <= 2004&
                         start >= 2002), 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator, -start), 
           yend = reorder(operator, -start)
           )) +
  theme_classic() +
  geom_segment() +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("operator")

ggplot(IHS_data_for_output %>% 
         dplyr::filter(start <= 2006&
                         start >= 2005), 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator, -start), 
           yend = reorder(operator, -start)
           )) +
  theme_classic() +
  geom_segment() +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("operator")

IHS_data_for_output %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()

```



### HB_data {.tabset}

#### Merger list

```{r, echo=FALSE}
merger_list <-
  matching_pair_year_HBdata %>% 
  dplyr::select(
    seller_name,
    buyer_name,
    end
  ) %>% 
  dplyr::rename(
    `Seller` = seller_name,
    `Buyer` = buyer_name,
    `Year` = end
  )

merger_list %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()

merger_list %>% 
  kableExtra::kbl(
    format = "latex",
    booktabs = TRUE,
    escape = FALSE,
    linesep = ""
  ) %>% 
  kableExtra::save_kable(
    file = here::here("figuretable/merger_list_HB.tex")
  )
```


#### Summary statistics

```{r, echo=FALSE}
seller_data <-
  matching_pair_year_HBdata %>% 
  dplyr::select(
    #seller_name,
    seller_operator_age_normalized,
    seller_cumsum_TEU_normalized
  ) %>% 
  dplyr::rename(
    `Age (Normalized)` = seller_operator_age_normalized,
    `Size TEU (Normalized)` = seller_cumsum_TEU_normalized
  )
buyer_data <-
  matching_pair_year_HBdata %>% 
  dplyr::select(
    #buyer_name,
    buyer_operator_age_normalized,
    buyer_cumsum_TEU_normalized
  ) %>% 
  dplyr::rename(
    `Age (Normalized)` = buyer_operator_age_normalized,
    `Size TEU (Normalized)` = buyer_cumsum_TEU_normalized
  )
target_date_HBdata <-
  rbind(
    seller_data,
    buyer_data
    ) %>% 
  dplyr::mutate(
    data = "HB (2006-2022)"
  )
f <- 
  (`Age (Normalized)` +
     `Size TEU (Normalized)`) ~ 
  N + (mean + sd + min + max)*Arguments(na.rm = TRUE)
modelsummary::datasummary(
  f,
  data = target_date_HBdata
  )
target_date_HBdata %>% 
  modelsummary::datasummary(
    f,
    escape = FALSE,
    data = .,
    output = "latex_tabular"
  ) %>% 
  gsub("\\multicolumn.*\\\\", "", .) %>% 
  kableExtra::save_kable(
    file = here::here("figuretable/summary_statistics_of_firms_HB.tex")
  )
```






#### Overall Transition

```{r, echo=FALSE}
operator_level_entry_exit_merger_HBdata_for_output <-
  operator_level_entry_exit_merger_HBdata %>% 
  dplyr::mutate(
    merging_firm_color =
      ifelse(is.na(merging_firm) == 1,
             operator_name,
             merging_firm)
  )

ggplot(operator_level_entry_exit_merger_HBdata_for_output, 
       aes(x = start,
           xend = end + 1, 
           y = reorder(operator_name, -start), 
           yend = reorder(operator_name, -start)
           )) +
  geom_segment(aes(colour=merging_firm)) +
  theme_classic() +
  #theme(legend.position = "none") +
  theme(axis.text.y=element_text(size=rel(0.2))) +
  xlab("Year") +
  ylab("Operator name")
operator_level_entry_exit_merger_HBdata_for_output %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()
```




## Distance distribution

```{r, echo=FALSE}
distance_data_CIY <-
  matching_pair_year_CIY %>% 
  dplyr::select(
    seller_name,
    buyer_name,
    seller_lat,
    seller_lon,
    buyer_lat,
    buyer_lon,
  ) %>% 
  dplyr::mutate(
    `Distance between firms' countries (1000km)` = 
      acos(
        sin(seller_lat)*sin(buyer_lat) + 
          cos(seller_lat) * cos(buyer_lat) *
          cos(seller_lon - buyer_lon)
        ) * 6378.137/ 1000 
      # sqrt(
      #   abs(seller_lat - buyer_lat)^2 + 
      #     abs(seller_lon - buyer_lon)^2
      # )
  ) %>% 
  dplyr::mutate(
    data = 
      "CIY(1966-1990)"
  )
distance_data_IHS <-
  matching_pair_year_IHS %>% 
  dplyr::select(
    seller_name,
    buyer_name,
    seller_lat,
    seller_lon,
    buyer_lat,
    buyer_lon,
  ) %>% 
  dplyr::mutate(
    `Distance between firms' countries (1000km)` = 
      acos(
        sin(seller_lat)*sin(buyer_lat) + 
          cos(seller_lat) * cos(buyer_lat) *
          cos(seller_lon - buyer_lon)
        ) * 6378.137/ 1000 
  ) %>% 
  dplyr::mutate(
    data = 
      "IHS(1991-2005)"
  )
distance_data_HB <-
  matching_pair_year_HBdata %>% 
  dplyr::select(
    seller_name,
    buyer_name,
    seller_lat,
    seller_lon,
    buyer_lat,
    buyer_lon,
  ) %>% 
  dplyr::mutate(
    `Distance between firms' countries (1000km)` = 
      acos(
        sin(seller_lat)*sin(buyer_lat) + 
          cos(seller_lat) * cos(buyer_lat) *
          cos(seller_lon - buyer_lon)
        ) * 6378.137/ 1000 
  ) %>% 
  dplyr::mutate(
    data = 
      "HB(2006-2022)"
  )

distance_data <-
  rbind(
    distance_data_CIY,
    distance_data_IHS,
    distance_data_HB
  )

x <-
  ggplot(
    distance_data, 
    aes(`Distance between firms' countries (1000km)`,
        shape = data, color = data)
    ) +
  stat_ecdf(geom = "step", alpha = 0.6)  +
  theme_classic() + 
  scale_color_viridis_d() +
  theme(legend.position = 'top',
        legend.text = element_text(size=6)) +
  ylab("CDF") +
  xlim(0, 20.4)
x
figure_name <- 
  "../figuretable/distance_cdf.png"
ggsave(filename = figure_name,
       plot = x,
       device = "png",
       width = 4,
       height = 3)
```


## Size distribution

```{r, echo=FALSE}
size_age_data <-
  rbind(
    target_date_CIY,
    target_date_IHS,
    target_date_HBdata
    )
x <-
  ggplot(
    size_age_data, 
    aes(`Size TEU (Normalized)`,
        shape = data, color = data)
    ) +
  stat_ecdf(geom = "step", alpha = 0.6)  +
  theme_classic() + 
  scale_color_viridis_d() +
  theme(legend.position = 'top',
        legend.text = element_text(size=6)) +
  ylab("CDF") +
  xlim(0, 1)
x
figure_name <- 
  "../figuretable/normalized_size_cdf.png"
ggsave(filename = figure_name,
       plot = x,
       device = "png",
       width = 4,
       height = 3)
```

## Age distribution

```{r, echo=FALSE}
x <-
  ggplot(
    size_age_data, 
    aes(`Age (Normalized)`,
        shape = data, color = data)
    ) +
  stat_ecdf(geom = "step", alpha = 0.6)  +
  theme_classic() + 
  scale_color_viridis_d() +
  theme(legend.position = 'top',
        legend.text = element_text(size=6)) +
  ylab("CDF") +
  xlim(0, 1)
x
figure_name <- 
  "../figuretable/normalized_age_cdf.png"
ggsave(filename = figure_name,
       plot = x,
       device = "png",
       width = 4,
       height = 3)
```
